# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
        ('news', '0003_auto_20161123_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hitcount.HitCount'),
        ),
    ]
