# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='', max_length=60),
        ),
    ]
