# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170425_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(choices=[(0, 'Directivo'), (1, 'Cientifico'), (2, 'Tecnico')], default=2, max_length=1),
        ),
    ]
