# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170425_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=60, verbose_name='Email'),
        ),
    ]
