# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('0', 'Mujer'), ('1', 'Hombre')], default=1, max_length=1, verbose_name='Genero'),
        ),
    ]
