# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 03:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
