# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170509_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(default='', max_length=400, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='link',
            field=models.CharField(default='', max_length=400, verbose_name='Enlace'),
        ),
    ]
