# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170509_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(default='', max_length=400, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='link',
            field=models.CharField(default='', max_length=400, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
    ]
