# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 03:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170509_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Mini-Biografia'),
        ),
        migrations.AddField(
            model_name='person',
            name='projects',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Proyectos'),
        ),
    ]
