# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 03:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170531_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
    ]
