# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 03:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170531_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Indice'),
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Mini-Biografia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace Web Personal'),
        ),
        migrations.AlterField(
            model_name='person',
            name='projects',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Proyectos'),
        ),
    ]
