# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170531_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('author', models.CharField(max_length=300, verbose_name='Autor(es)')),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicacion')),
                ('link', models.CharField(max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('author', models.CharField(max_length=200, verbose_name='Autor(es)')),
                ('date', models.DateTimeField(verbose_name='Fecha de Publicacion')),
                ('info', models.TextField(null=True, verbose_name='Informacion')),
                ('link', models.CharField(max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Enlace')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion')),
                ('university', models.CharField(blank=True, default='', max_length=200, verbose_name='Universidad')),
            ],
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='history',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Descripcion'),
        ),
    ]
