# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_paper_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Enlace'),
        ),
    ]
