# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170602_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(null=True, upload_to=main.models.thesis_doc_directory_path, verbose_name='Archivo'),
        ),
    ]
