# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170602_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Enlace Web Personal'),
        ),
    ]
